### GET
GET {{API_BASE_URL}}/spaces
Authorization: {{TOKEN}}
### GET by id
GET {{API_BASE_URL}}/spaces?id=d9262dc2-e6b7-4baf-a29a-d6d400616e0f
Authorization: {{TOKEN}}
### POST
POST {{API_BASE_URL}}/spaces
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "location": "Paris",
  "name": "Best location"
}
### PUT
PUT {{API_BASE_URL}}/spaces?id=d9262dc2-e6b7-4baf-a29a-d6d400616e0f
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "location": "Tunis",
  "name": "So Great location"
}
### DELETE
DELETE {{API_BASE_URL}}/spaces?id=ab0290e1-06a6-4600-8346-c2a84c56ab40
Authorization: {{TOKEN}}


